[versions]
googleauth = "1.22.0"
netty = '4.1.100.Final'
# Keep the following references of tcnative version in sync whenever it's updated:
#   SECURITY.md
nettytcnative = '2.0.61.Final'
opencensus = "0.31.1"
protobuf = "3.25.1"

[libraries]
android-annotations = "com.google.android:annotations:4.1.1.4"
androidx-annotation = "androidx.annotation:annotation:1.7.0"
androidx-core = "androidx.core:core:1.12.0"
androidx-lifecycle-common = "androidx.lifecycle:lifecycle-common:2.6.2"
androidx-lifecycle-service = "androidx.lifecycle:lifecycle-service:2.6.2"
androidx-test-core = "androidx.test:core:1.5.0"
androidx-test-ext-junit = "androidx.test.ext:junit:1.1.5"
androidx-test-rules = "androidx.test:rules:1.5.0"
animalsniffer = "org.codehaus.mojo:animal-sniffer:1.23"
animalsniffer-annotations = "org.codehaus.mojo:animal-sniffer-annotations:1.23"
auto-value = "com.google.auto.value:auto-value:1.10.4"
auto-value-annotations = "com.google.auto.value:auto-value-annotations:1.10.4"
checkstyle = "com.puppycrawl.tools:checkstyle:10.12.5"
commons-math3 = "org.apache.commons:commons-math3:3.6.1"
conscrypt = "org.conscrypt:conscrypt-openjdk-uber:2.5.2"
cronet-api = "org.chromium.net:cronet-api:119.6045.31"
cronet-embedded = "org.chromium.net:cronet-embedded:119.6045.31"
errorprone-annotations = "com.google.errorprone:error_prone_annotations:2.23.0"
errorprone-core = "com.google.errorprone:error_prone_core:2.23.0"
google-api-protos = "com.google.api.grpc:proto-google-common-protos:2.29.0"
google-auth-credentials = { module = "com.google.auth:google-auth-library-credentials", version.ref = "googleauth" }
google-auth-oauth2Http = { module = "com.google.auth:google-auth-library-oauth2-http", version.ref = "googleauth" }
# Release notes: https://cloud.google.com/logging/docs/release-notes
google-cloud-logging = "com.google.cloud:google-cloud-logging:3.15.14"
gson = "com.google.code.gson:gson:2.10.1"
guava = "com.google.guava:guava:32.1.3-android"
guava-betaChecker = "com.google.guava:guava-beta-checker:1.0"
guava-testlib = "com.google.guava:guava-testlib:32.1.3-android"
# JRE version is needed for projects where its a transitive dependency, f.e. gcp-observability.
# May be different from the -android version.
guava-jre = "com.google.guava:guava:32.1.3-jre"
hdrhistogram = "org.hdrhistogram:HdrHistogram:2.1.12"
j2objc-annotations = " com.google.j2objc:j2objc-annotations:2.8"
jakarta-servlet-api = "jakarta.servlet:jakarta.servlet-api:5.0.0"
javax-annotation = "org.apache.tomcat:annotations-api:6.0.53"
javax-servlet-api = "javax.servlet:javax.servlet-api:4.0.1"
jetty-client = "org.eclipse.jetty:jetty-client:10.0.20"
jetty-http2-server = "org.eclipse.jetty.http2:http2-server:11.0.20"
jetty-http2-server10 = "org.eclipse.jetty.http2:http2-server:10.0.20"
jetty-servlet = "org.eclipse.jetty:jetty-servlet:11.0.20"
jetty-servlet10 = "org.eclipse.jetty:jetty-servlet:10.0.20"
jsr305 = "com.google.code.findbugs:jsr305:3.0.2"
junit = "junit:junit:4.13.2"
lincheck = "org.jetbrains.kotlinx:lincheck:2.14.1"
# Update notes / 2023-07-19 sergiitk:
#    Couldn't update to 5.4.0, updated to the last in 4.x line. Version 5.x breaks some tests.
#    Error log: https://github.com/grpc/grpc-java/pull/10359#issuecomment-1632834435
# Update notes / 2023-10-09 temawi:
#    4.11.0 Has been breaking the android integration tests as mockito now uses streams
#    (not available in API levels < 24). https://github.com/grpc/grpc-java/issues/10457
mockito-android = "org.mockito:mockito-android:4.4.0"
mockito-core = "org.mockito:mockito-core:4.4.0"
netty-codec-http2 = { module = "io.netty:netty-codec-http2", version.ref = "netty" }
netty-handler-proxy = { module = "io.netty:netty-handler-proxy", version.ref = "netty" }
netty-tcnative = { module = "io.netty:netty-tcnative-boringssl-static", version.ref = "nettytcnative" }
netty-tcnative-classes = { module = "io.netty:netty-tcnative-classes", version.ref = "nettytcnative" }
netty-transport-epoll = { module = "io.netty:netty-transport-native-epoll", version.ref = "netty" }
netty-unix-common = { module = "io.netty:netty-transport-native-unix-common", version.ref = "netty" }
okhttp = "com.squareup.okhttp:okhttp:2.7.5"
# okio 3.5+ uses Kotlin 1.9+ which requires Android Gradle Plugin 9+
okio = "com.squareup.okio:okio:3.4.0"
opencensus-api = { module = "io.opencensus:opencensus-api", version.ref = "opencensus" }
opencensus-contrib-grpc-metrics = { module = "io.opencensus:opencensus-contrib-grpc-metrics", version.ref = "opencensus" }
opencensus-exporter-stats-stackdriver = { module = "io.opencensus:opencensus-exporter-stats-stackdriver", version.ref = "opencensus" }
opencensus-exporter-trace-stackdriver = { module = "io.opencensus:opencensus-exporter-trace-stackdriver", version.ref = "opencensus" }
opencensus-impl = { module = "io.opencensus:opencensus-impl", version.ref = "opencensus" }
opencensus-proto = "io.opencensus:opencensus-proto:0.2.0"
opentelemetry-api = "io.opentelemetry:opentelemetry-api:1.36.0"
opentelemetry-sdk-testing = "io.opentelemetry:opentelemetry-sdk-testing:1.36.0"
perfmark-api = "io.perfmark:perfmark-api:0.26.0"
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
protobuf-java-util = { module = "com.google.protobuf:protobuf-java-util", version.ref = "protobuf" }
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf" }
protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
re2j = "com.google.re2j:re2j:1.7"
robolectric = "org.robolectric:robolectric:4.11.1"
signature-android = "net.sf.androidscents.signature:android-api-level-19:4.4.2_r4"
signature-java = "org.codehaus.mojo.signature:java18:1.0"
tomcat-embed-core = "org.apache.tomcat.embed:tomcat-embed-core:10.1.23"
tomcat-embed-core9 = "org.apache.tomcat.embed:tomcat-embed-core:9.0.89"
truth = "com.google.truth:truth:1.1.5"
undertow-servlet = "io.undertow:undertow-servlet:2.2.32.Final"
undertow-servlet-jakartaee9 = "io.undertow:undertow-servlet:2.3.13.Final"

# Do not update: Pinned to the last version supporting Java 8.
# See https://checkstyle.sourceforge.io/releasenotes.html#Release_10.1
checkstylejava8 = "com.puppycrawl.tools:checkstyle:9.3"
# See https://github.com/google/error-prone/releases/tag/v2.11.0
errorprone-corejava8 = "com.google.errorprone:error_prone_core:2.10.0"
