[versions]
netty = '4.1.127.Final'
# Keep the following references of tcnative version in sync whenever it's updated:
#   SECURITY.md
nettytcnative = '2.0.74.Final'
opencensus = "0.31.1"
# Not upgrading to 4.x as it is not yet ABI compatible.
# https://github.com/protocolbuffers/protobuf/issues/17247
protobuf = "3.25.8"

[libraries]
android-annotations = "com.google.android:annotations:4.1.1.4"
# androidx-annotation 1.9.1+ uses Kotlin and requires Android Gradle Plugin 9+
# checkForUpdates: androidx-annotation:1.9.0
androidx-annotation = "androidx.annotation:annotation:1.9.0"
# 1.15.0 requires libraries and applications that depend on it to compile against
# version 35 or later of the Android APIs.
# checkForUpdates: androidx-core:1.13.+
androidx-core = "androidx.core:core:1.13.1"
# androidx-lifecycle 2.9+ requires Java 17
androidx-lifecycle-common = "androidx.lifecycle:lifecycle-common:2.8.7"
androidx-lifecycle-service = "androidx.lifecycle:lifecycle-service:2.8.7"
androidx-test-core = "androidx.test:core:1.6.1"
androidx-test-ext-junit = "androidx.test.ext:junit:1.2.1"
androidx-test-rules = "androidx.test:rules:1.6.1"
animalsniffer = "org.codehaus.mojo:animal-sniffer:1.24"
animalsniffer-annotations = "org.codehaus.mojo:animal-sniffer-annotations:1.24"
assertj-core = "org.assertj:assertj-core:3.27.3"
auto-value = "com.google.auto.value:auto-value:1.11.0"
auto-value-annotations = "com.google.auto.value:auto-value-annotations:1.11.0"
checkstyle = "com.puppycrawl.tools:checkstyle:10.21.2"
commons-math3 = "org.apache.commons:commons-math3:3.6.1"
conscrypt = "org.conscrypt:conscrypt-openjdk-uber:2.5.2"
cronet-api = "org.chromium.net:cronet-api:119.6045.31"
cronet-embedded = "org.chromium.net:cronet-embedded:119.6045.31"
errorprone-annotations = "com.google.errorprone:error_prone_annotations:2.36.0"
# error-prone 2.32.0+ require Java 17+
# checkForUpdates: errorprone-core:2.31.+
errorprone-core = "com.google.errorprone:error_prone_core:2.31.0"
google-api-protos = "com.google.api.grpc:proto-google-common-protos:2.59.2"
# google-auth-library 1.25.0+ requires error_prone_annotations 2.31.0+, which
# breaks the Android build
# checkForUpdates: google-auth-credentials:1.24.+
google-auth-credentials = "com.google.auth:google-auth-library-credentials:1.24.1"
# checkForUpdates: google-auth-oauth2Http:1.24.+
google-auth-oauth2Http = "com.google.auth:google-auth-library-oauth2-http:1.24.1"
# Release notes: https://cloud.google.com/logging/docs/release-notes
google-cloud-logging = "com.google.cloud:google-cloud-logging:3.23.1"
# 2.13.0 requires error_prone_annotations:2.37.0, but we are stuck with 2.36.0
# checkForUpdates: gson:2.12.+
gson = "com.google.code.gson:gson:2.12.1"
# 33.4.8 requires com.google.errorprone:error_prone_annotations:2.36.0
guava = "com.google.guava:guava:33.4.8-android"
guava-betaChecker = "com.google.guava:guava-beta-checker:1.0"
guava-testlib = "com.google.guava:guava-testlib:33.4.8-android"
# JRE version is needed for projects where its a transitive dependency, f.e. gcp-observability.
# May be different from the -android version.
guava-jre = "com.google.guava:guava:33.4.8-jre"
hdrhistogram = "org.hdrhistogram:HdrHistogram:2.2.2"
# 6.0.0+ use java.lang.Deprecated forRemoval and since from Java 9
# checkForUpdates: jakarta-servlet-api:5.+
jakarta-servlet-api = "jakarta.servlet:jakarta.servlet-api:5.0.0"
javax-servlet-api = "javax.servlet:javax.servlet-api:4.0.1"
# 12.0.0+ require Java 17+
# checkForUpdates: jetty-client:11.+
jetty-client = "org.eclipse.jetty:jetty-client:11.0.24"
jetty-http2-server = "org.eclipse.jetty.http2:jetty-http2-server:12.0.23"
jetty-http2-server10 = "org.eclipse.jetty.http2:http2-server:10.0.20"
jetty-servlet = "org.eclipse.jetty.ee10:jetty-ee10-servlet:12.0.16"
jetty-servlet10 = "org.eclipse.jetty:jetty-servlet:10.0.20"
jsr305 = "com.google.code.findbugs:jsr305:3.0.2"
junit = "junit:junit:4.13.2"
lincheck = "org.jetbrains.lincheck:lincheck:3.2"
# Update notes / 2023-07-19 sergiitk:
#    Couldn't update to 5.4.0, updated to the last in 4.x line. Version 5.x breaks some tests.
#    Error log: https://github.com/grpc/grpc-java/pull/10359#issuecomment-1632834435
# Update notes / 2023-10-09 temawi:
#    4.11.0 Has been breaking the android integration tests as mockito now uses streams
#    (not available in API levels < 24). https://github.com/grpc/grpc-java/issues/10457
mockito-android = "org.mockito:mockito-android:4.4.0"
mockito-core = "org.mockito:mockito-core:4.4.0"
netty-codec-http2 = { module = "io.netty:netty-codec-http2", version.ref = "netty" }
netty-handler-proxy = { module = "io.netty:netty-handler-proxy", version.ref = "netty" }
netty-tcnative = { module = "io.netty:netty-tcnative-boringssl-static", version.ref = "nettytcnative" }
netty-tcnative-classes = { module = "io.netty:netty-tcnative-classes", version.ref = "nettytcnative" }
netty-transport-epoll = { module = "io.netty:netty-transport-native-epoll", version.ref = "netty" }
netty-unix-common = { module = "io.netty:netty-transport-native-unix-common", version.ref = "netty" }
okhttp = "com.squareup.okhttp:okhttp:2.7.5"
# okio 3.5+ uses Kotlin 1.9+ which requires Android Gradle Plugin 9+
# checkForUpdates: okio:3.4.+
okio = "com.squareup.okio:okio:3.4.0"
opencensus-api = { module = "io.opencensus:opencensus-api", version.ref = "opencensus" }
opencensus-contrib-grpc-metrics = { module = "io.opencensus:opencensus-contrib-grpc-metrics", version.ref = "opencensus" }
opencensus-exporter-stats-stackdriver = { module = "io.opencensus:opencensus-exporter-stats-stackdriver", version.ref = "opencensus" }
opencensus-exporter-trace-stackdriver = { module = "io.opencensus:opencensus-exporter-trace-stackdriver", version.ref = "opencensus" }
opencensus-impl = { module = "io.opencensus:opencensus-impl", version.ref = "opencensus" }
opentelemetry-api = "io.opentelemetry:opentelemetry-api:1.52.0"
opentelemetry-exporter-prometheus = "io.opentelemetry:opentelemetry-exporter-prometheus:1.52.0-alpha"
opentelemetry-gcp-resources = "io.opentelemetry.contrib:opentelemetry-gcp-resources:1.48.0-alpha"
opentelemetry-sdk-extension-autoconfigure = "io.opentelemetry:opentelemetry-sdk-extension-autoconfigure:1.52.0"
opentelemetry-sdk-testing = "io.opentelemetry:opentelemetry-sdk-testing:1.52.0"
perfmark-api = "io.perfmark:perfmark-api:0.27.0"
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
protobuf-java-util = { module = "com.google.protobuf:protobuf-java-util", version.ref = "protobuf" }
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf" }
protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
re2j = "com.google.re2j:re2j:1.8"
robolectric = "org.robolectric:robolectric:4.15.1"
s2a-proto = "com.google.s2a.proto.v2:s2a-proto:0.1.2"
signature-android = "net.sf.androidscents.signature:android-api-level-21:5.0.1_r2"
signature-java = "org.codehaus.mojo.signature:java18:1.0"
# 11.0.0+ require Java 17+
# checkForUpdates: tomcat-embed-core:10.+
tomcat-embed-core = "org.apache.tomcat.embed:tomcat-embed-core:10.1.31"
# checkForUpdates: tomcat-embed-core9:9.+
tomcat-embed-core9 = "org.apache.tomcat.embed:tomcat-embed-core:9.0.89"
truth = "com.google.truth:truth:1.4.4"
# checkForUpdates: undertow-servlet22:2.2.+
undertow-servlet22 = "io.undertow:undertow-servlet:2.2.37.Final"
undertow-servlet = "io.undertow:undertow-servlet:2.3.18.Final"

# checkstyle 10.0+ requires Java 11+
# See https://checkstyle.sourceforge.io/releasenotes_old_8-35_10-26.html#Release_10.0
# checkForUpdates: checkstylejava8:9.+
checkstylejava8 = "com.puppycrawl.tools:checkstyle:9.3"
# 2.11.0+ requires JDK 11+ (See https://github.com/google/error-prone/releases/tag/v2.11.0)
# checkForUpdates: errorprone-corejava8:2.10.+
errorprone-corejava8 = "com.google.errorprone:error_prone_core:2.10.0"
